export const initialFields = [
  { text: "Hoja", field: "hoja", completed: false, focused: true, section: "encabezado" },
  { text: "Tipo de documento", field: "tipo_doc", completed: false, focused: false, section: "encabezado" },
  { text: "Punto de venta", field: "serie_docum", completed: false, focused: false, section: "encabezado" },
  { text: "Numero del documento", field: "nro_docum", completed: false, focused: false, section: "encabezado" },
  { text: "CUIT", field: "nro_dgi", completed: false, focused: false, section: "encabezado" },
  { text: "CUIT Empresa", field: "nro_dgi_empresa", completed: false, focused: false, section: "encabezado" },
  { text: "Razon social", field: "razon_social", completed: false, focused: false, section: "encabezado" },
  { text: "Fecha del documento", field: "fec_doc", completed: false, focused: false, section: "encabezado" },
  { text: "Fecha de vencimiento", field: "fec_vencimiento", completed: false, focused: false, section: "encabezado" },
  { text: "Fecha periodo Desde", field: "fec_periodo_dd", completed: false, focused: false, section: "encabezado" },
  { text: "Fecha periodo Hasta", field: "fec_periodo_ht", completed: false, focused: false, section: "encabezado" },
  { text: "Condicion de venta", field: "cond_fpago", completed: false, focused: false, section: "encabezado" },
  { text: "Condicion frente al iva", field: "cond_IVA", completed: false, focused: false, section: "encabezado" },
  { text: "Domicilio comercial", field: "dir_tit", completed: false, focused: false, section: "encabezado" },
  { text: "Orden de compra", field: "orden_compra", completed: false, focused: false, section: "encabezado" },
  { text: "Sector de filas", field: "filas", completed: false, focused: false, section: "encabezado" },
  { text: "Subtotal", field: "subtotal", completed: false, focused: false, section: "pie" },
  { text: "Otros tributos", field: "otros_tributos", completed: false, focused: false, section: "pie" },
  { text: "Fletes", field: "fletes", completed: false, focused: false, section: "pie" },
  { text: "Porcentaje provincial", field: "porc_prov", completed: false, focused: false, section: "pie" },
  { text: "Importe provincial", field: "imp_prov", completed: false, focused: false, section: "pie" },
  { text: "Porcentaje IVA", field: "porc_iva", completed: false, focused: false, section: "pie" },
  { text: "Importe IVA", field: "imp_iva", completed: false, focused: false, section: "pie" },
  { text: "Total", field: "total", completed: false, focused: false, section: "pie" },
  { text: "CAE", field: "cae", completed: false, focused: false, section: "pie" },
  { text: "Fecha vencimiento CAE", field: "fec_vencimiento_cae", completed: false, focused: false, section: "pie" },
  { text: "Codigo", field: "cod_articulo", completed: false, focused: false, column: true },
  { text: "Aduana", field: "aduana", completed: false, focused: false, column: true },
  { text: "Lote", field: "lote", completed: false, focused: false, column: true },
  { text: "Vencimiento", field: "vencimiento", completed: false, focused: false, column: true },
  { text: "Producto", field: "nom_articulo", completed: false, focused: false, column: true },
  { text: "Cantidad", field: "cantidad", completed: false, focused: false, column: true },
  { text: "Unidad de medida", field: "cod_unidad", completed: false, focused: false, column: true },
  { text: "Precio unitario", field: "precio", completed: false, focused: false, column: true },
  { text: "Porcentaje Bonificacion", field: "porc_bonif", completed: false, focused: false, column: true },
  { text: "Importe Bonificacion", field: "imp_desc", completed: false, focused: false, column: true },
  { text: "Subtotal", field: "imp_stot_mo", completed: false, focused: false, column: true }
]
